spring:
  application:
    name: planner
  datasource:
    url: jdbc:mysql://localhost:3306/my_planner?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: myPlannerPool
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      auto-commit: true
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        use_sql_comments: false
        jdbc:
          time_zone: UTC
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
server:
  port: 8080